### ISSUE TITLE
This is cool!

### ISSUE THREAD

**Issue by dalpaka** [datavorous/GrudgePixel#1]
I've tried it and its awesome cool github pages by the way!

(Also I've noticed youre using raylib which i am using too to build a game where each pixel is indivisually rendered like Noita so i was wondering if you can help me)

**Comment by datavorous** [comment]
Thanks! what should i improve upon? Please give some more feedbacks!

Also i had made a sand simulation, much like Noita, without gameplay, few years back; would love to follow your progress on it!
